# -----------------------------------------------------
# THEME CONFIGURATION
# -----------------------------------------------------
source = $HOME/.config/hypr/macchiato.conf

$accent = $mauve
$accentAlpha = $mauveAlpha
$font = JetBrainsMono Nerd Font

# -----------------------------------------------------
# GENERAL
# -----------------------------------------------------
general {
    disable_loading_bar = true
    hide_cursor = true
}

# -----------------------------------------------------
# BACKGROUND
# -----------------------------------------------------
background {
    monitor =
    path = ~/.config/hypr/hyprlock.png
    blur_passes = 2
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# -----------------------------------------------------
# DAY (Top Element)
# -----------------------------------------------------
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%A")"
    color = $text
    font_size = 60
    font_family = $font
    position = 0, 350
    halign = center
    valign = center
}

# -----------------------------------------------------
# DATE (Under Day)
# -----------------------------------------------------
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%d %B")"
    color = $subtext1
    font_size = 30
    font_family = $font
    position = 0, 250
    halign = center
    valign = center
}

# -----------------------------------------------------
# TIME (Under Date)
# -----------------------------------------------------
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%I:%M")</span>"
    color = $subtext0
    font_size = 20
    font_family = $font
    position = 0, 190
    halign = center
    valign = center
}

# -----------------------------------------------------
# USER LABEL
# -----------------------------------------------------
label {
    monitor =
    text =   $USER
    color = $accent
    font_size = 18
    font_family = $font
    position = 0, -130
    halign = center
    valign = center
}

# -----------------------------------------------------
# INPUT FIELD
# -----------------------------------------------------
input-field {
    monitor =
    size = 300, 60
    outline_thickness = 4
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    
    # Catppuccin Colors
    outer_color = $accent
    inner_color = $surface0
    font_color = $text
    
    fade_on_empty = false
    placeholder_text = <span foreground="##$textAlpha">Password</span>
    hide_input = false
    
    check_color = $accent
    fail_color = $red
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    capslock_color = $yellow
    
    position = 0, -210
    halign = center
    valign = center
}